server:
  host: "0.0.0.0"
  port: ":8080"
bot:
  token: "6512097371:AAF0WBJgjVQ0YEZjCFSf5qzxTg0t0R56SdU"
  webhookLink: "https://19d7-203-205-52-97.ngrok.io/"
database:
  connectionURI: "postgres://telegrambot:botpassword@localhost:5432/telegrambot?sslmode=disable&pool_max_conns=100&pool_max_conn_lifetime=1h"
migration:
  # https://github.com/golang-migrate/migrate/blob/master/database/postgres/README.md
  databaseUrl: "postgres://telegrambot:botpassword@localhost:5432/telegrambot?sslmode=disable&search_path=public&x-migrations-table=schema_migrations"
